#!/usr/bin/env bash
# shellcheck disable=SC2086
# show subdomains.
#
domains() {
    # print informtion about 
    names=("www" "lb-01" "web-01" "web-02")
    if [ -z "$2" ]
    then
	for i in "${names[@]}"
	do
	    dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1| awk '{split($0, elements, "."); print "The subdomain " elements[1] " is a " $4 " record and points to " $5}'
	done
    else
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1| awk '{split($0, elements, "."); print "The subdomain " elements[1] " is a " $4 " record and points to " $5}'
    fi
}
domains "$1" "$2"
