#!/usr/bin/env bash
#this scrip install and cofigure a NGINX web server.
apt-get -y update
apt-get -y install nginx
service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
#sed -i '1 s/^\tlisten [0-9]/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
#sed -i '1 s/^\tlisten [[]/\tlisten [::]:80 default_server;/' /etc/nginx/sites-enabled/default
service nginx restart
