#!/usr/bin/env bash
#this scrip install and cofigure a NGINX web server.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html


set_301="location /redirect_me {\n\treturn 301 https://www.youtube.com;\n\t}"
sudo sed -i "/server_name _/a$set_301" /etc/nginx/sites-enabled/default
sudo service nginx restart
