#!/usr/bin/env bash
#this scrip install and cofigure a NGINX web server.
sudo apt-get -y update
apt-get -y install nginx
service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '1 s/^\tlisten [0-9]/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i '1 s/^\tlisten [[]/\tlisten [::]:80 default_server;/' /etc/nginx/sites-enabled/default
set_301="\\\tlocation  /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}\n"
sudo sed -i "30i $set_301" /etc/nginx/sites-enabled/default
sudo service nginx restart
