#!/usr/bin/env bash
#this scrip install and cofigure a NGINX web server.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i '1 s/^\tlisten [0-9]/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default
sed -i '1 s/^\tlisten [[]/\tlisten [::]:80 default_server;/' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
set_404="error_page 404 /404.html;\n\tlocation = /404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n\t}"
sed -i "/server_name _/a$set_404" /etc/nginx/sites-enabled/default
set_301="location = /redirect_me {\n\treturn 301 www.youtube.com;\n\t}"
sed -i "/server_name _/a$set_301" /etc/nginx/sites-enabled/default
sudo service nginx restart
