#!/bin/bash
#this make a bakup of database.
exportname="backup.sql"
database="tyrell_corp"
pwd=$1
mysqldump -u root -p"$pwd" --all-databases > $exportname
now="$(date +'%d-%m-%Y')"
tar -czvf "$now".tar.gz backup.sql
