#!/usr/bin/env bash
# this kill process the nginx.
sudo pkill -f nginx & wait $!
sudo service nginx start
sudo sed -i "s/listen listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen [::]:80 default_server ipv6only=on;/listen [::]:80 default_server;/" /etc/nginx/sites-available/default
suod service nginx restart
