#!/usr/bin/env bash
# this kill process the nginx.
/etc/init.d/nginx status
sudo pkill -f nginx & wait "$!"
#sudo service nginx start
grep -lr listen /etc/nginx/* | xargs sed -i "s/8080/80/"
sudo service nginx restart
