#!/usr/bin/env bash
#this script print holberton School and hi at de nineth repetition.
i=0
while [ $i -lt 10 ]
do
    echo "Holberton School"
    if [ $i == 8 ]
    then
	echo "Hi"
    fi
    i=$((i+1))
done
