#!/usr/bin/env bash
#this change the permiser of nginx to no sudo user.
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/^#user.*/user nginx;/" /etc/nginx/nginx.conf
sudo chmod 000 /etc/nginx/nginx.conf
sudo deluser nginx sudo
sudo service nginx restart
