#!/usr/bin/env bash
#this change the permiser of nginx to no sudo user.
pkill apache2
chmod 400 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
